service: hellow-serverless

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2

functions:
  createStory:
    handler: src/stories.createStory
    events:
      - http:
          path: stories
          method: post
    timeout: 10
  readStories:
    handler: src/stories.readStories
    events:
      - http:
          path: stories
          method: get
  readStory:
    handler: src/stories.readStory
    events:
      - http:
          path: stories/{id}
          method: get
  updateStory:
    handler: src/stories.updateStory
    events:
      - http:
          path: stories/{id}
          method: patch
  deleteStory:
    handler: src/stories.deleteStory
    events:
      - http:
          path: stories/{id}
          method: delete
